name: Ruby-Rspec

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 1.9.3-p551
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
